# Generated by Django 5.2.3 on 2026-04-09 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('released', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_type', models.CharField(choices=[('admirals_order', "Admiral's Order"), ('character', 'Character'), ('creature', 'Creature'), ('device', 'Device'), ('effect', 'Effect'), ('epic_event', 'Epic Event'), ('interrupt', 'Interrupt'), ('jedi_test', 'Jedi Test'), ('location', 'Location'), ('objective', 'Objective'), ('starship', 'Starship'), ('vehicle', 'Vehicle'), ('weapon', 'Weapon')], max_length=20)),
                ('side', models.CharField(choices=[('L', 'Light Side'), ('D', 'Dark Side')], max_length=1)),
                ('rarity', models.CharField(blank=True, choices=[('C', 'C'), ('C1', 'C1'), ('C2', 'C2'), ('U', 'U'), ('U1', 'U1'), ('U2', 'U2'), ('R', 'R'), ('R1', 'R1'), ('R2', 'R2'), ('UR', 'UR'), ('XR', 'XR'), ('F', 'F'), ('PM', 'PM')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='swccgdb.set')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveSmallIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='swccgdb.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'card')},
            },
        ),
    ]
