# Generated by Django 5.2.3 on 2026-04-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedcard',
            name='copies',
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='copies_bb',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Black Border (Limited)'),
        ),
        migrations.AddField(
            model_name='ownedcard',
            name='copies_wb',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='White Border (Unlimited)'),
        ),
    ]
