# Generated by Django 5.2.3 on 2026-04-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0002_remove_ownedcard_copies_ownedcard_copies_bb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sets/'),
        ),
    ]
