# Generated by Django 5.2.3 on 2026-04-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0003_set_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('admirals_order', "Admiral's Order"), ('alien_character', 'Alien'), ('rebel_character', 'Rebel'), ('droid_character', 'Droid'), ('imperial_character', 'IMPERIAL'), ('creature', 'Creature'), ('device', 'Device'), ('effect', 'Effect'), ('epic_event', 'Epic Event'), ('used_interrupt', 'Used Interrupt'), ('lost_interrupt', 'Lost Interrupt'), ('jedi_test', 'Jedi Test'), ('location', 'Location'), ('objective', 'Objective'), ('starship', 'Starship'), ('vehicle', 'Vehicle'), ('weapon', 'Weapon')], max_length=20),
        ),
    ]
