# Generated by Django 5.2.3 on 2026-04-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0006_alter_card_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
