# Generated by Django 5.2.3 on 2026-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0007_remove_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='secondary_card_type',
            field=models.CharField(blank=True, choices=[('admirals_order', "Admiral's Order"), ('alien_character', 'Alien'), ('rebel_character', 'Rebel'), ('droid_character', 'Droid'), ('imperial_character', 'Imperial'), ('device', 'Device'), ('effect', 'Effect'), ('epic_event', 'Epic Event'), ('interrupt', 'Interrupt'), ('jedi_test', 'Jedi Test'), ('location', 'Location'), ('objective', 'Objective'), ('starship', 'Starship'), ('vehicle', 'Vehicle'), ('weapon', 'Weapon')], max_length=20, null=True),
        ),
    ]
