# Generated by Django 5.2.3 on 2026-04-22 19:00

import webpfield.fields
import webpfield.webp_storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0007_remove_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='image',
            field=webpfield.fields.WebPField(blank=True, null=True, storage=webpfield.webp_storage.WebPStorage(), upload_to='sets/'),
        ),
    ]
