# Generated by Django 5.2.3 on 2026-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0010_alter_card_card_type_alter_card_secondary_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('high_republic_character', 'High Republic'), ('jedi_master_character', 'Jedi Master'), ('jedi_test', 'Jedi Test'), ('rebel_character', 'Rebel'), ('alien_character', 'Alien'), ('droid_character', 'Droid'), ('imperial_character', 'Imperial'), ('admirals_order', "Admiral's Order"), ('defensive_shield', 'Defensive Shield'), ('device', 'Device'), ('effect', 'Effect'), ('epic_event', 'Epic Event'), ('interrupt', 'Interrupt'), ('location', 'Location'), ('objective', 'Objective'), ('starship', 'Starship'), ('vehicle', 'Vehicle'), ('weapon', 'Weapon')], max_length=25),
        ),
        migrations.AlterField(
            model_name='card',
            name='secondary_card_type',
            field=models.CharField(blank=True, choices=[('high_republic_character', 'High Republic'), ('jedi_master_character', 'Jedi Master'), ('jedi_test', 'Jedi Test'), ('rebel_character', 'Rebel'), ('alien_character', 'Alien'), ('droid_character', 'Droid'), ('imperial_character', 'Imperial'), ('admirals_order', "Admiral's Order"), ('defensive_shield', 'Defensive Shield'), ('device', 'Device'), ('effect', 'Effect'), ('epic_event', 'Epic Event'), ('interrupt', 'Interrupt'), ('location', 'Location'), ('objective', 'Objective'), ('starship', 'Starship'), ('vehicle', 'Vehicle'), ('weapon', 'Weapon')], max_length=25, null=True),
        ),
    ]
