# Generated by Django 5.2.3 on 2026-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0012_deck_deckcard_deck_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('jedi_master_character', 'Jedi Master'), ('jedi_test', 'Jedi Test'), ('rebel_character', 'Rebel'), ('republic_character', 'Republic'), ('alien_character', 'Alien'), ('droid_character', 'Droid'), ('dark_jedi_master_character', 'Dark Jedi Master'), ('imperial_character', 'Imperial'), ('sith_character', 'Sith'), ('admirals_order', "Admiral's Order"), ('creature', 'Creature'), ('defensive_shield', 'Defensive Shield'), ('device', 'Device'), ('effect', 'Effect'), ('epic_event', 'Epic Event'), ('game_aid', 'Game Aid'), ('interrupt', 'Interrupt'), ('location', 'Location'), ('objective', 'Objective'), ('starship', 'Starship'), ('vehicle', 'Vehicle'), ('weapon', 'Weapon')], max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='secondary_card_type',
            field=models.CharField(blank=True, choices=[('jedi_master_character', 'Jedi Master'), ('jedi_test', 'Jedi Test'), ('rebel_character', 'Rebel'), ('republic_character', 'Republic'), ('alien_character', 'Alien'), ('droid_character', 'Droid'), ('dark_jedi_master_character', 'Dark Jedi Master'), ('imperial_character', 'Imperial'), ('sith_character', 'Sith'), ('admirals_order', "Admiral's Order"), ('creature', 'Creature'), ('defensive_shield', 'Defensive Shield'), ('device', 'Device'), ('effect', 'Effect'), ('epic_event', 'Epic Event'), ('game_aid', 'Game Aid'), ('interrupt', 'Interrupt'), ('location', 'Location'), ('objective', 'Objective'), ('starship', 'Starship'), ('vehicle', 'Vehicle'), ('weapon', 'Weapon')], max_length=30, null=True),
        ),
    ]
