# Generated by Django 5.2.3 on 2026-08-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccgdb', '0014_alter_card_card_type_alter_card_secondary_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_text', models.TextField(blank=True)),
                ('lore', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('deploy_cost', models.CharField(blank=True, max_length=10)),
                ('destiny', models.CharField(blank=True, max_length=10)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('ability', models.CharField(blank=True, max_length=10)),
                ('armor', models.CharField(blank=True, max_length=10)),
                ('forfeit', models.CharField(blank=True, max_length=10)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='swccgdb.card')),
            ],
        ),
    ]
