apiVersion: v1
kind: ConfigMap
metadata:
  name: website-config
  namespace: steyaertsite
data:
  PIPELINE: "production"
  ALLOWED_HOSTS: "movies.steyaert.xyz"
  CSRF_TRUSTED_ORIGINS: "https://movies.steyaert.xyz"
  DATABASE_ENGINE: "postgresql"
  DATABASE_NAME: "steyaertsite_db"
  DATABASE_USERNAME: "steyaertsite_user"
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
