# Generated by Django 5.2.3 on 2025-06-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NR', 'NR'), ('TV', 'TV')], max_length=6)),
                ('disk', models.CharField(choices=[('4k', '4K Ultra HD'), ('blu-ray', 'Blu-Ray'), ('dvd', 'DVD')], max_length=8)),
            ],
        ),
    ]
