# Generated by Django 5.2.3 on 2026-02-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'rating', 'disk')},
        ),
    ]
