# Generated by Django 5.2.3 on 2026-03-01 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_alter_movie_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomMovieResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movies', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='moviedb_ran_created_721dc8_idx')],
            },
        ),
    ]
