from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("cards/", views.all_cards, name="all_cards"),
    path("owned/", views.owned_cards, name="owned_cards"),
    path("missing/", views.missing_cards, name="missing_cards"),
    path("collection/edit/", views.edit_collection, name="edit_collection"),
    path("cards/add/", views.add_card, name="add_card"),
    path("cards/<int:card_id>/edit/", views.edit_card, name="edit_card"),
    path("sets/", views.sets_list, name="sets_list"),
    path("sets/add/", views.add_set, name="add_set"),
    path("sets/<int:set_id>/edit/", views.edit_set, name="edit_set"),
    path("cards/<int:card_id>/add-copy/<str:border>/", views.add_copy, name="add_copy"),
    path("cards/<int:card_id>/remove-copy/<str:border>/", views.remove_copy, name="remove_copy"),
    path("collection/save/", views.save_collection, name="save_collection"),
    path("collection/export/", views.export_collection_by_set, name="export_collection_by_set"),
    path("collection/import/", views.import_collection_by_set, name="import_collection_by_set"),
    path("tutorial/", views.tutorial, name="tutorial"),
    path("decks/", views.deck_list, name="deck_list"),
    path("decks/new/", views.deck_new, name="deck_new"),
    path("decks/<uuid:deck_id>/", views.deck_detail, name="deck_detail"),
    path("decks/<uuid:deck_id>/edit/", views.deck_edit, name="deck_edit"),
    path("decks/<uuid:deck_id>/delete/", views.deck_delete, name="deck_delete"),
    path("decks/<uuid:deck_id>/toggle-public/", views.deck_toggle_public, name="deck_toggle_public"),
    path("decks/<uuid:deck_id>/save/", views.deck_save_toggle, name="deck_save_toggle"),
    path("decks/<uuid:deck_id>/add-card/", views.deck_add_card, name="deck_add_card"),
    path("decks/<uuid:deck_id>/remove-card/", views.deck_remove_card, name="deck_remove_card"),
    path("decks/<uuid:deck_id>/update-card/", views.deck_update_card, name="deck_update_card"),
]